# Generated by Django 3.2.9 on 2021-11-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='home',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
